Add @types/node as a regular dep
Still getting the error:

Cannot find name 'require'. Do you need to install type definitions for
node? Try `npm i --save-dev @types/node`.